apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-frontend
  template:
    metadata:
      labels:
        app: client-frontend
    spec:
      containers:
      - name: client-frontend
        image: food-delivery-microservices-main-client-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5174
---
apiVersion: v1
kind: Service
metadata:
  name: client-frontend
spec:
  type: NodePort
  selector:
    app: client-frontend
  ports:
    - port: 5174
      targetPort: 5174
      nodePort: 30002