apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-delivery-ingress
  namespace: food-delivery
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  # Backend Services
  - host: api.food-delivery.local
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 8001
      - path: /catalog
        pathType: Prefix
        backend:
          service:
            name: catalog-service
            port:
              number: 8002
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 8003
  # Frontend Services
  - host: food-delivery.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-frontend
            port:
              number: 5174
  - host: admin.food-delivery.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-frontend
            port:
              number: 5173
