apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-secrets
  namespace: food-delivery
type: Opaque
stringData:
  # JWT Secret Key (same for all services)
  JWT_SECRET_KEY: "ippt-project-dev-secret-key-fixed-for-local-development-2024"
  
  # Telegram Bot Token
  TELEGRAM_BOT_TOKEN: "8322734845:AAGQDbGSboYa9qP5G6H-omfAnnPL0GDiwQE"
