apiVersion: v1
kind: Service
metadata:
  name: client-frontend
  namespace: food-delivery
  labels:
    app: client-frontend
    service: frontend
spec:
  type: ClusterIP
  ports:
  - port: 5174
    targetPort: 5174
    protocol: TCP
    name: http
  selector:
    app: client-frontend
